/** The convention families of the catalogue's regions and the helpers the release stages are checked with
 * (Producto 24R2A, 24R2B). Regions that write numbers the same way (decimal, group character, grouping, minimum
 * grouping) share every amount-field behaviour; regions that write dates and times the same way (the date, day-month
 * and 24-hour templates and the clock) share every date string. The stages themselves are `region-stages.ts`; the
 * per-family iPhone sheet is docs/region-families.md, generated by `npm run regions:families` from the functions here
 * and kept in sync by a test. Pure; no React. */
import { REGIONS, type RegionCode } from './locale.ts';
import { REGION_RELEASE_STAGES, RELEASED_BY_STAGES, writesNativeDigits, type RegionReleaseStage, type StageStatus } from './region-stages.ts';

export { REGION_RELEASE_STAGES, RELEASED_BY_STAGES, writesNativeDigits, type RegionReleaseStage, type StageStatus };

/** A separator as it can be read in a report: ".", ",", "'" as themselves, a space by its code point. */
const visible = (char: string) => /^[.,']$/.test(char) ? char : 'U+' + char.codePointAt(0)!.toString(16).toUpperCase().padStart(4, '0');

/** How a region writes numbers: "decimal ',' · group '.' · 3/3 · min 1". Regions with one number family type,
 * paste and group amounts identically, so one of them on the iPhone checks them all. */
export function numberFamily(code: RegionCode): string {
  const c = REGIONS[code];
  return `decimal '${c.decimal}' · group '${visible(c.group)}' · 3/${c.secondaryGrouping} · min ${c.minimumGroupingDigits}`;
}

/** How a region writes dates and times: "d/M/y · d/M · HH:mm · 24 h" (a no-break space shown as "␣"). */
export function dateFamily(code: RegionCode): string {
  const c = REGIONS[code];
  const shown = (template: string) => template.replace(/\u00A0/g, '␣');
  return `${shown(c.datePattern)} · ${shown(c.dayMonthPattern)} · ${c.timePattern} · ${c.hour12 ? '12 h' : '24 h'}`;
}

/** The families a stage covers. */
export function stageFamilies(stage: RegionReleaseStage): { numbers: string[]; dates: string[] } {
  return { numbers: [...new Set(stage.regions.map(numberFamily))].sort(), dates: [...new Set(stage.regions.map(dateFamily))].sort() };
}

/** The regions of the stages already released: what `RELEASED_REGIONS` is. */
export function releasedByStages(stages: readonly RegionReleaseStage[] = REGION_RELEASE_STAGES): RegionCode[] {
  return stages.filter(stage => stage.status === 'released').flatMap(stage => stage.regions);
}

/** The stage a region is planned in, if any. */
export function stageOf(code: RegionCode, stages: readonly RegionReleaseStage[] = REGION_RELEASE_STAGES): RegionReleaseStage | null {
  return stages.find(stage => stage.regions.includes(code)) ?? null;
}
