// npm run regions:families — writes docs/region-families.md, the short iPhone sheet of Producto 24R2B: one row per
// number family (typing, the pad's decimal key, a big amount, a paste that must be refused) and the date writings worth
// a glance, in Spanish and English, with every expected string computed by the app's own formatters and amount field.
// `-- --check` compares without writing (tests/region-families.node.ts runs it). No dependency, no network.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const MOBILE = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(MOBILE, '..', '..', 'docs', 'region-families.md');
const load = path => import(pathToFileURL(join(MOBILE, path)).href);

/** Where a family is checked: the first released region of this list that belongs to it (well-known places first). */
const PREFERRED = ['GB', 'DE', 'FR', 'CH', 'IN', 'ES', 'PL', 'SE', 'BR', 'MX', 'JP', 'CA'];
/** Date writings to glance at: one region for each shape the audit touched (spaces and closing periods, a dotted time,
 * an unpadded hour, year-first, month-first, hyphens, a 12-hour clock). */
const DATE_GLANCE = ['KR', 'HU', 'HR', 'SK', 'CZ', 'FI', 'DK', 'JP', 'CA', 'LT', 'PA', 'MX', 'ES', 'DE', 'GB'];

const visible = text => text.replace(/ /g, '⍽').replace(/ /g, '·');

export async function familySheet() {
  const { RELEASED_REGIONS, REGIONS } = await load('src/i18n/locale.ts');
  const { REGION_RELEASE_STAGES, numberFamily, dateFamily } = await load('src/i18n/region-release.ts');
  const { bindLocale } = await load('src/i18n/bind.ts');
  const { AmountInput } = await load('src/ui/money-input.ts');
  const { regionDisplayName } = await load('src/i18n/regions.ts');
  const typed = (region, keys) => {
    const input = new AmountInput('', bindLocale(`es-${region}`).amountFormat, 'ARS');
    for (const key of keys) input.change(input.view.text.slice(0, input.view.caret) + key + input.view.text.slice(input.view.caret), input.view.caret + 1);
    return input.view.text;
  };
  const families = new Map();
  for (const code of RELEASED_REGIONS) {
    const family = numberFamily(code);
    if (!families.has(family)) families.set(family, []);
    families.get(family).push(code);
  }
  const lines = [
    '# Region families: the iPhone sheet (Producto 24R2B)',
    '',
    '<!-- GENERATED by apps/mobile/scripts/regions/families.mjs (`npm run regions:families`). Do not edit: the expected',
    'strings are the app\'s own formatters and amount field; tests/region-families.node.ts fails when this file is stale. -->',
    '',
    'How to use: FinanzApp Dev from the branch (Metro, no flag), Más → Región on «Según el dispositivo», iOS Settings →',
    'General → Language & Region → Region set to the region named. Check once in Spanish and once in English (Más →',
    'Idioma). `·` is a no-break space, `⍽` a narrow no-break space; on screen both look like a space. Every value was',
    'verified automatically for all released regions (tests/region-families.node.ts); the iPhone confirms the keyboard,',
    'the drawing and VoiceOver. Record results in docs/mobile-device-checklist.md (Producto 24R2B).',
    '',
    '## 1. Amounts, one region per number family',
    '',
    'Nuevo gasto in pesos: type 1 2 3 4 5 6 7, the pad\'s decimal key, 8 9. Then delete the last three characters and',
    'the group separator before them with the delete key (the digit before it goes). Then paste the refused text into',
    'an empty field: the field keeps its value and says why. VoiceOver reads the typed amount as the field shows it; a',
    'saved movement is read ungrouped ("1234567,89 pesos" / "1234567.89 pesos").',
    '',
    '| Family | Released regions | Check in | Typed | A saved amount | Refused paste |',
    '| --- | --- | --- | --- | --- | --- |',
  ];
  for (const [family, codes] of families) {
    const region = PREFERRED.find(code => codes.includes(code)) ?? codes.find(code => !['AR', 'US'].includes(code)) ?? codes[0];
    const i = bindLocale(`es-${region}`);
    lines.push(`| \`${family}\` | ${codes.length} | ${regionDisplayName(region, 'es')} (${region}) | \`${visible(typed(region, '1234567,89'))}\` | \`${visible(i.moneyText(123456789012, 'ARS'))}\` | \`1${REGIONS[region].decimal}000\` |`);
  }
  lines.push('', '## 2. Dates and times to glance at', '',
    'A movement\'s detail (date), Reportes → a day of the month (day and month), Más → Copias de seguridad (date and time).', '',
    '| Region | Date | Day and month | Date and time, Spanish | Date and time, English |', '| --- | --- | --- | --- | --- |');
  for (const region of DATE_GLANCE.filter(code => RELEASED_REGIONS.includes(code))) {
    const es = bindLocale(`es-${region}`), en = bindLocale(`en-${region}`);
    lines.push(`| ${regionDisplayName(region, 'es')} (${region}) | \`${visible(es.formatNumericDate('2026-09-05'))}\` | \`${visible(es.formatDayMonth('2026-09-05'))}\` | \`${visible(es.formatDateTime('2026-09-22T09:03:00'))}\` | \`${visible(en.formatDateTime('2026-09-22T21:03:00'))}\` |`);
  }
  const dateFamilies = new Map();
  for (const code of RELEASED_REGIONS) {
    const family = dateFamily(code);
    if (!dateFamilies.has(family)) dateFamilies.set(family, []);
    dateFamilies.get(family).push(code);
  }
  lines.push('', `## 3. Every date family (${dateFamilies.size}), verified automatically`, '',
    'Date · day and month · 24-hour time · clock (`␣` a no-break space). Checked for every region in tests/region-families.node.ts;', 'no iPhone row needed beyond section 2.', '');
  for (const [family, codes] of [...dateFamilies].sort((a, b) => b[1].length - a[1].length || (a[0] < b[0] ? -1 : 1))) lines.push(`- \`${family}\`: ${codes.join(', ')}`);
  lines.push('', '## 4. Not released, and why', '');
  for (const stage of REGION_RELEASE_STAGES.filter(item => item.status === 'blocked')) {
    lines.push(`- **${stage.id}** (${stage.regions.length}): ${stage.regions.join(', ')}. ${stage.blocker}`);
  }
  return lines.join('\n') + '\n';
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const sheet = await familySheet();
  if (process.argv.includes('--check')) {
    const current = (() => { try { return readFileSync(OUT, 'utf8'); } catch { return ''; } })();
    console.log(current === sheet ? 'Region family sheet up to date.' : 'docs/region-families.md is stale: run npm run regions:families.');
    process.exit(current === sheet ? 0 : 1);
  }
  writeFileSync(OUT, sheet);
  console.log('Wrote docs/region-families.md.');
}
