/* GENERATED by apps/mobile/scripts/currency/generate.mjs (`npm run currency:generate`). Do not edit.
 * Sources: ISO 4217 List One published 2026-09-17 (SIX Financial Information AG, the ISO 4217
 * maintenance agency) and Unicode CLDR 48.2.0 (cldr-json; data under the Unicode License v3,
 * LICENSES/Unicode-3.0.txt). Exact files and sha256: apps/mobile/scripts/currency/sources.lock.json.
 * What each field means and how to update: docs/currency.md. This file is data; packages/domain/
 * currency.ts is the API. `minorUnit` is ISO 4217's and is the ledger exponent of a currency once it
 * can be stored; `digits`/`rounding`/`cashDigits`/`cashRounding` are CLDR's formatting data (never a
 * reason to round a recorded amount). */

/** fiat: a currency of a country or monetary union; fund: an ISO fund code (not money a person spends);
 * metal, unit (units of account, SDR), test and none (XXX): never money in the ledger. */
export type CurrencyKind = 'fiat' | 'fund' | 'metal' | 'unit' | 'test' | 'none';
/** ready: fiat with complete data in every language this build carries; incomplete: fiat missing some
 * data (listed in `missing`); excluded: not fiat. Whether a currency can be stored is decided in
 * currency.ts (LEDGER_CURRENCIES), never here. */
export type CurrencyDataStatus = 'ready' | 'incomplete' | 'excluded';
export interface CurrencyRecord {
  /** ISO 4217 numeric code, three digits. */
  readonly numeric: string;
  /** ISO 4217 minor unit (decimal places of the minor unit); null when ISO says N.A. (not fiat). */
  readonly minorUnit: number | null;
  /** CLDR: fraction digits normally shown, and the rounding increment in those digits (0 = none). */
  readonly digits: number;
  readonly rounding: number;
  /** CLDR: the same for cash (Swiss 0.05, Danish 0.50); presentation of cash only, never the ledger. */
  readonly cashDigits: number;
  readonly cashRounding: number;
  readonly kind: CurrencyKind;
  readonly status: CurrencyDataStatus;
  /** What `status: incomplete` lacks: "name:<language>" (CLDR has no name in that language) or "tender"
   * (no CLDR territory lists it as current legal tender). */
  readonly missing: readonly string[];
  /** CLDR root symbol, unique among fiat currencies ("US$", "CA$", "€", "JP¥"), or the code itself. */
  readonly symbol: string;
  /** CLDR narrow symbol ("$", "¥", "kr"): ambiguous on purpose, only for a region's own currency. */
  readonly narrowSymbol: string;
  /** ISO 3166 regions where CLDR lists it as current legal tender (search aliases, never a default). */
  readonly territories: readonly string[];
}

export const ISO_4217_PUBLISHED = "2026-09-17";
export const CLDR_VERSION = "48.2.0";

/** Every code of ISO 4217 List One, sorted. */
export const CURRENCY_CODES = [
  "AED", "AFN", "ALL", "AMD", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT",
  "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD",
  "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUP",
  "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP",
  "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF",
  "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR",
  "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD",
  "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN",
  "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN",
  "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD",
  "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SOS", "SRD", "SSP", "STN", "SVC", "SYP",
  "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX",
  "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAD",
  "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XCG", "XDR", "XOF", "XPD",
  "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWG",
] as const;
export type IsoCurrencyCode = typeof CURRENCY_CODES[number];

export const CURRENCY_DATA: { readonly [Code in IsoCurrencyCode]: CurrencyRecord } = {
  AED: { numeric: "784", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "AED", narrowSymbol: "AED", territories: ["AE"] },
  AFN: { numeric: "971", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "AFN", narrowSymbol: "؋", territories: ["AF"] },
  ALL: { numeric: "008", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "ALL", narrowSymbol: "ALL", territories: ["AL"] },
  AMD: { numeric: "051", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "AMD", narrowSymbol: "֏", territories: ["AM"] },
  AOA: { numeric: "973", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "AOA", narrowSymbol: "Kz", territories: ["AO"] },
  ARS: { numeric: "032", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "ARS", narrowSymbol: "$", territories: ["AR"] },
  AUD: { numeric: "036", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "A$", narrowSymbol: "$", territories: ["AU","CC","CX","HM","KI","NF","NR","TV"] },
  AWG: { numeric: "533", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "AWG", narrowSymbol: "AWG", territories: ["AW"] },
  AZN: { numeric: "944", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "AZN", narrowSymbol: "₼", territories: ["AZ"] },
  BAM: { numeric: "977", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BAM", narrowSymbol: "KM", territories: ["BA"] },
  BBD: { numeric: "052", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BBD", narrowSymbol: "$", territories: ["BB"] },
  BDT: { numeric: "050", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BDT", narrowSymbol: "৳", territories: ["BD"] },
  BHD: { numeric: "048", minorUnit: 3, digits: 3, rounding: 0, cashDigits: 3, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BHD", narrowSymbol: "BHD", territories: ["BH"] },
  BIF: { numeric: "108", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BIF", narrowSymbol: "BIF", territories: ["BI"] },
  BMD: { numeric: "060", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BMD", narrowSymbol: "$", territories: ["BM"] },
  BND: { numeric: "096", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BND", narrowSymbol: "$", territories: ["BN"] },
  BOB: { numeric: "068", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BOB", narrowSymbol: "Bs", territories: ["BO"] },
  BOV: { numeric: "984", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "BOV", narrowSymbol: "BOV", territories: [] },
  BRL: { numeric: "986", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "R$", narrowSymbol: "R$", territories: ["BR"] },
  BSD: { numeric: "044", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BSD", narrowSymbol: "$", territories: ["BS"] },
  BTN: { numeric: "064", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BTN", narrowSymbol: "BTN", territories: ["BT"] },
  BWP: { numeric: "072", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BWP", narrowSymbol: "P", territories: ["BW"] },
  BYN: { numeric: "933", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BYN", narrowSymbol: "BYN", territories: ["BY"] },
  BZD: { numeric: "084", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "BZD", narrowSymbol: "$", territories: ["BZ"] },
  CAD: { numeric: "124", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 5, kind: "fiat", status: "ready", missing: [], symbol: "CA$", narrowSymbol: "$", territories: ["CA"] },
  CDF: { numeric: "976", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "CDF", narrowSymbol: "CDF", territories: ["CD"] },
  CHE: { numeric: "947", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "CHE", narrowSymbol: "CHE", territories: [] },
  CHF: { numeric: "756", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 5, kind: "fiat", status: "ready", missing: [], symbol: "CHF", narrowSymbol: "CHF", territories: ["CH","LI"] },
  CHW: { numeric: "948", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "CHW", narrowSymbol: "CHW", territories: [] },
  CLF: { numeric: "990", minorUnit: 4, digits: 4, rounding: 0, cashDigits: 4, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "CLF", narrowSymbol: "CLF", territories: [] },
  CLP: { numeric: "152", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "CLP", narrowSymbol: "$", territories: ["CL"] },
  CNY: { numeric: "156", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "CN¥", narrowSymbol: "¥", territories: ["CN"] },
  COP: { numeric: "170", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "COP", narrowSymbol: "$", territories: ["CO"] },
  COU: { numeric: "970", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "COU", narrowSymbol: "COU", territories: [] },
  CRC: { numeric: "188", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "CRC", narrowSymbol: "₡", territories: ["CR"] },
  CUP: { numeric: "192", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "CUP", narrowSymbol: "$", territories: ["CU"] },
  CVE: { numeric: "132", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "CVE", narrowSymbol: "CVE", territories: ["CV"] },
  CZK: { numeric: "203", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "CZK", narrowSymbol: "Kč", territories: ["CZ"] },
  DJF: { numeric: "262", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "DJF", narrowSymbol: "DJF", territories: ["DJ"] },
  DKK: { numeric: "208", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 50, kind: "fiat", status: "ready", missing: [], symbol: "DKK", narrowSymbol: "kr", territories: ["DK","FO","GL"] },
  DOP: { numeric: "214", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "DOP", narrowSymbol: "$", territories: ["DO"] },
  DZD: { numeric: "012", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "DZD", narrowSymbol: "DZD", territories: ["DZ"] },
  EGP: { numeric: "818", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "EGP", narrowSymbol: "E£", territories: ["EG"] },
  ERN: { numeric: "232", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "ERN", narrowSymbol: "ERN", territories: ["ER"] },
  ETB: { numeric: "230", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "ETB", narrowSymbol: "ETB", territories: ["ET"] },
  EUR: { numeric: "978", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "€", narrowSymbol: "€", territories: ["AD","AT","AX","BE","BG","BL","CY","DE","EA","EE","ES","EU","FI","FR","GF","GP","GR","HR","IC","IE","IT","LT","LU","LV","MC","ME","MF","MQ","MT","NL","PM","PT","RE","SI","SK","SM","TF","VA","XK","YT"] },
  FJD: { numeric: "242", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "FJD", narrowSymbol: "$", territories: ["FJ"] },
  FKP: { numeric: "238", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "FKP", narrowSymbol: "£", territories: ["FK"] },
  GBP: { numeric: "826", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "£", narrowSymbol: "£", territories: ["GB","GG","GS","IM","JE","TA"] },
  GEL: { numeric: "981", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "GEL", narrowSymbol: "₾", territories: ["GE"] },
  GHS: { numeric: "936", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "GHS", narrowSymbol: "GH₵", territories: ["GH"] },
  GIP: { numeric: "292", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "GIP", narrowSymbol: "£", territories: ["GI"] },
  GMD: { numeric: "270", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "GMD", narrowSymbol: "GMD", territories: ["GM"] },
  GNF: { numeric: "324", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "GNF", narrowSymbol: "FG", territories: ["GN"] },
  GTQ: { numeric: "320", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "GTQ", narrowSymbol: "Q", territories: ["GT"] },
  GYD: { numeric: "328", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "GYD", narrowSymbol: "$", territories: ["GY"] },
  HKD: { numeric: "344", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "HK$", narrowSymbol: "$", territories: ["HK"] },
  HNL: { numeric: "340", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "HNL", narrowSymbol: "L", territories: ["HN"] },
  HTG: { numeric: "332", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "HTG", narrowSymbol: "HTG", territories: ["HT"] },
  HUF: { numeric: "348", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 5, kind: "fiat", status: "ready", missing: [], symbol: "HUF", narrowSymbol: "Ft", territories: ["HU"] },
  IDR: { numeric: "360", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "IDR", narrowSymbol: "Rp", territories: ["ID"] },
  ILS: { numeric: "376", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "₪", narrowSymbol: "₪", territories: ["IL","PS"] },
  INR: { numeric: "356", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "₹", narrowSymbol: "₹", territories: ["BT","IN"] },
  IQD: { numeric: "368", minorUnit: 3, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "IQD", narrowSymbol: "IQD", territories: ["IQ"] },
  IRR: { numeric: "364", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "IRR", narrowSymbol: "IRR", territories: ["IR"] },
  ISK: { numeric: "352", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "ISK", narrowSymbol: "kr", territories: ["IS"] },
  JMD: { numeric: "388", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "JMD", narrowSymbol: "$", territories: ["JM"] },
  JOD: { numeric: "400", minorUnit: 3, digits: 3, rounding: 0, cashDigits: 3, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "JOD", narrowSymbol: "JOD", territories: ["JO","PS"] },
  JPY: { numeric: "392", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "JP¥", narrowSymbol: "¥", territories: ["JP"] },
  KES: { numeric: "404", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "KES", narrowSymbol: "KES", territories: ["KE"] },
  KGS: { numeric: "417", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "KGS", narrowSymbol: "⃀", territories: ["KG"] },
  KHR: { numeric: "116", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "KHR", narrowSymbol: "៛", territories: ["KH"] },
  KMF: { numeric: "174", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "KMF", narrowSymbol: "CF", territories: ["KM"] },
  KPW: { numeric: "408", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "KPW", narrowSymbol: "₩", territories: ["KP"] },
  KRW: { numeric: "410", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "₩", narrowSymbol: "₩", territories: ["KR"] },
  KWD: { numeric: "414", minorUnit: 3, digits: 3, rounding: 0, cashDigits: 3, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "KWD", narrowSymbol: "KWD", territories: ["KW"] },
  KYD: { numeric: "136", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "KYD", narrowSymbol: "$", territories: ["KY"] },
  KZT: { numeric: "398", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "KZT", narrowSymbol: "₸", territories: ["KZ"] },
  LAK: { numeric: "418", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "LAK", narrowSymbol: "₭", territories: ["LA"] },
  LBP: { numeric: "422", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "LBP", narrowSymbol: "L£", territories: ["LB"] },
  LKR: { numeric: "144", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "LKR", narrowSymbol: "Rs", territories: ["LK"] },
  LRD: { numeric: "430", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "LRD", narrowSymbol: "$", territories: ["LR"] },
  LSL: { numeric: "426", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "LSL", narrowSymbol: "LSL", territories: ["LS"] },
  LYD: { numeric: "434", minorUnit: 3, digits: 3, rounding: 0, cashDigits: 3, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "LYD", narrowSymbol: "LYD", territories: ["LY"] },
  MAD: { numeric: "504", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MAD", narrowSymbol: "MAD", territories: ["EH","MA"] },
  MDL: { numeric: "498", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MDL", narrowSymbol: "MDL", territories: ["MD"] },
  MGA: { numeric: "969", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MGA", narrowSymbol: "Ar", territories: ["MG"] },
  MKD: { numeric: "807", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MKD", narrowSymbol: "MKD", territories: ["MK"] },
  MMK: { numeric: "104", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MMK", narrowSymbol: "K", territories: ["MM"] },
  MNT: { numeric: "496", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MNT", narrowSymbol: "₮", territories: ["MN"] },
  MOP: { numeric: "446", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MOP", narrowSymbol: "MOP", territories: ["MO"] },
  MRU: { numeric: "929", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MRU", narrowSymbol: "MRU", territories: ["MR"] },
  MUR: { numeric: "480", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MUR", narrowSymbol: "Rs", territories: ["MU"] },
  MVR: { numeric: "462", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MVR", narrowSymbol: "MVR", territories: ["MV"] },
  MWK: { numeric: "454", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MWK", narrowSymbol: "MWK", territories: ["MW"] },
  MXN: { numeric: "484", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MX$", narrowSymbol: "$", territories: ["MX"] },
  MXV: { numeric: "979", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "MXV", narrowSymbol: "MXV", territories: [] },
  MYR: { numeric: "458", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MYR", narrowSymbol: "RM", territories: ["MY"] },
  MZN: { numeric: "943", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "MZN", narrowSymbol: "MZN", territories: ["MZ"] },
  NAD: { numeric: "516", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "NAD", narrowSymbol: "$", territories: ["NA"] },
  NGN: { numeric: "566", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "NGN", narrowSymbol: "₦", territories: ["NG"] },
  NIO: { numeric: "558", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "NIO", narrowSymbol: "C$", territories: ["NI"] },
  NOK: { numeric: "578", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "NOK", narrowSymbol: "kr", territories: ["BV","NO","SJ"] },
  NPR: { numeric: "524", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "NPR", narrowSymbol: "Rs", territories: ["NP"] },
  NZD: { numeric: "554", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "NZ$", narrowSymbol: "$", territories: ["CK","NU","NZ","PN","TK"] },
  OMR: { numeric: "512", minorUnit: 3, digits: 3, rounding: 0, cashDigits: 3, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "OMR", narrowSymbol: "OMR", territories: ["OM"] },
  PAB: { numeric: "590", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "PAB", narrowSymbol: "PAB", territories: ["PA"] },
  PEN: { numeric: "604", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "PEN", narrowSymbol: "PEN", territories: ["PE"] },
  PGK: { numeric: "598", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "PGK", narrowSymbol: "PGK", territories: ["PG"] },
  PHP: { numeric: "608", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "₱", narrowSymbol: "₱", territories: ["PH"] },
  PKR: { numeric: "586", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "PKR", narrowSymbol: "Rs", territories: ["PK"] },
  PLN: { numeric: "985", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "PLN", narrowSymbol: "zł", territories: ["PL"] },
  PYG: { numeric: "600", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "PYG", narrowSymbol: "₲", territories: ["PY"] },
  QAR: { numeric: "634", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "QAR", narrowSymbol: "QAR", territories: ["QA"] },
  RON: { numeric: "946", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "RON", narrowSymbol: "lei", territories: ["RO"] },
  RSD: { numeric: "941", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "RSD", narrowSymbol: "RSD", territories: ["RS"] },
  RUB: { numeric: "643", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "RUB", narrowSymbol: "₽", territories: ["RU"] },
  RWF: { numeric: "646", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "RWF", narrowSymbol: "RF", territories: ["RW"] },
  SAR: { numeric: "682", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SAR", narrowSymbol: "SAR", territories: ["SA"] },
  SBD: { numeric: "090", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SBD", narrowSymbol: "$", territories: ["SB"] },
  SCR: { numeric: "690", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SCR", narrowSymbol: "SCR", territories: ["SC"] },
  SDG: { numeric: "938", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SDG", narrowSymbol: "SDG", territories: ["SD"] },
  SEK: { numeric: "752", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SEK", narrowSymbol: "kr", territories: ["SE"] },
  SGD: { numeric: "702", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SGD", narrowSymbol: "$", territories: ["SG"] },
  SHP: { numeric: "654", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SHP", narrowSymbol: "£", territories: ["AC","SH"] },
  SLE: { numeric: "925", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SLE", narrowSymbol: "SLE", territories: ["SL"] },
  SOS: { numeric: "706", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SOS", narrowSymbol: "SOS", territories: ["SO"] },
  SRD: { numeric: "968", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SRD", narrowSymbol: "$", territories: ["SR"] },
  SSP: { numeric: "728", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SSP", narrowSymbol: "£", territories: ["SS"] },
  STN: { numeric: "930", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "STN", narrowSymbol: "Db", territories: ["ST"] },
  SVC: { numeric: "222", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "incomplete", missing: ["tender"], symbol: "SVC", narrowSymbol: "SVC", territories: [] },
  SYP: { numeric: "760", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SYP", narrowSymbol: "£", territories: ["SY"] },
  SZL: { numeric: "748", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "SZL", narrowSymbol: "SZL", territories: ["SZ"] },
  THB: { numeric: "764", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "THB", narrowSymbol: "฿", territories: ["TH"] },
  TJS: { numeric: "972", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "TJS", narrowSymbol: "TJS", territories: ["TJ"] },
  TMT: { numeric: "934", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "TMT", narrowSymbol: "TMT", territories: ["TM"] },
  TND: { numeric: "788", minorUnit: 3, digits: 3, rounding: 0, cashDigits: 3, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "TND", narrowSymbol: "TND", territories: ["TN"] },
  TOP: { numeric: "776", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "TOP", narrowSymbol: "T$", territories: ["TO"] },
  TRY: { numeric: "949", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "TRY", narrowSymbol: "₺", territories: ["TR"] },
  TTD: { numeric: "780", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "TTD", narrowSymbol: "$", territories: ["TT"] },
  TWD: { numeric: "901", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "NT$", narrowSymbol: "$", territories: ["TW"] },
  TZS: { numeric: "834", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "TZS", narrowSymbol: "TZS", territories: ["TZ"] },
  UAH: { numeric: "980", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "UAH", narrowSymbol: "₴", territories: ["UA"] },
  UGX: { numeric: "800", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "UGX", narrowSymbol: "UGX", territories: ["UG"] },
  USD: { numeric: "840", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "US$", narrowSymbol: "$", territories: ["AS","BQ","DG","EC","FM","GU","HT","IO","MH","MP","PA","PR","PW","SV","TC","TL","UM","US","VG","VI","ZW"] },
  USN: { numeric: "997", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "USN", narrowSymbol: "USN", territories: [] },
  UYI: { numeric: "940", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "UYI", narrowSymbol: "UYI", territories: [] },
  UYU: { numeric: "858", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "UYU", narrowSymbol: "$", territories: ["UY"] },
  UYW: { numeric: "927", minorUnit: 4, digits: 4, rounding: 0, cashDigits: 4, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "UYW", narrowSymbol: "UYW", territories: [] },
  UZS: { numeric: "860", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "UZS", narrowSymbol: "UZS", territories: ["UZ"] },
  VED: { numeric: "926", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "incomplete", missing: ["name:es","tender"], symbol: "VED", narrowSymbol: "VED", territories: [] },
  VES: { numeric: "928", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "VES", narrowSymbol: "VES", territories: ["VE"] },
  VND: { numeric: "704", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "₫", narrowSymbol: "₫", territories: ["VN"] },
  VUV: { numeric: "548", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "VUV", narrowSymbol: "VUV", territories: ["VU"] },
  WST: { numeric: "882", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "WST", narrowSymbol: "WST", territories: ["WS"] },
  XAD: { numeric: "396", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fund", status: "excluded", missing: [], symbol: "XAD", narrowSymbol: "XAD", territories: [] },
  XAF: { numeric: "950", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "FCFA", narrowSymbol: "FCFA", territories: ["CF","CG","CM","GA","GQ","TD"] },
  XAG: { numeric: "961", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "metal", status: "excluded", missing: [], symbol: "XAG", narrowSymbol: "XAG", territories: [] },
  XAU: { numeric: "959", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "metal", status: "excluded", missing: [], symbol: "XAU", narrowSymbol: "XAU", territories: [] },
  XBA: { numeric: "955", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "unit", status: "excluded", missing: [], symbol: "XBA", narrowSymbol: "XBA", territories: [] },
  XBB: { numeric: "956", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "unit", status: "excluded", missing: [], symbol: "XBB", narrowSymbol: "XBB", territories: [] },
  XBC: { numeric: "957", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "unit", status: "excluded", missing: [], symbol: "XBC", narrowSymbol: "XBC", territories: [] },
  XBD: { numeric: "958", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "unit", status: "excluded", missing: [], symbol: "XBD", narrowSymbol: "XBD", territories: [] },
  XCD: { numeric: "951", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "EC$", narrowSymbol: "$", territories: ["AG","AI","DM","GD","KN","LC","MS","VC"] },
  XCG: { numeric: "532", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "Cg.", narrowSymbol: "Cg.", territories: ["CW","SX"] },
  XDR: { numeric: "960", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "unit", status: "excluded", missing: [], symbol: "XDR", narrowSymbol: "XDR", territories: [] },
  XOF: { numeric: "952", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "F CFA", narrowSymbol: "F CFA", territories: ["BF","BJ","CI","GW","ML","NE","SN","TG"] },
  XPD: { numeric: "964", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "metal", status: "excluded", missing: [], symbol: "XPD", narrowSymbol: "XPD", territories: [] },
  XPF: { numeric: "953", minorUnit: 0, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "CFPF", narrowSymbol: "CFPF", territories: ["NC","PF","WF"] },
  XPT: { numeric: "962", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "metal", status: "excluded", missing: [], symbol: "XPT", narrowSymbol: "XPT", territories: [] },
  XSU: { numeric: "994", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "unit", status: "excluded", missing: [], symbol: "XSU", narrowSymbol: "XSU", territories: [] },
  XTS: { numeric: "963", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "test", status: "excluded", missing: [], symbol: "XTS", narrowSymbol: "XTS", territories: [] },
  XUA: { numeric: "965", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "unit", status: "excluded", missing: [], symbol: "XUA", narrowSymbol: "XUA", territories: [] },
  XXX: { numeric: "999", minorUnit: null, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "none", status: "excluded", missing: [], symbol: "¤", narrowSymbol: "¤", territories: [] },
  YER: { numeric: "886", minorUnit: 2, digits: 0, rounding: 0, cashDigits: 0, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "YER", narrowSymbol: "YER", territories: ["YE"] },
  ZAR: { numeric: "710", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "ZAR", narrowSymbol: "R", territories: ["LS","NA","ZA"] },
  ZMW: { numeric: "967", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "ZMW", narrowSymbol: "ZK", territories: ["ZM"] },
  ZWG: { numeric: "924", minorUnit: 2, digits: 2, rounding: 0, cashDigits: 2, cashRounding: 0, kind: "fiat", status: "ready", missing: [], symbol: "ZWG", narrowSymbol: "ZWG", territories: ["ZW"] },
};
