import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { CLDR_VERSION, CURRENCY_CODES, ISO_4217_PUBLISHED, currenciesWithStatus, currencyRecord, currencyStatus, type IsoCurrencyCode } from '@finanzapp/domain';
import { CURRENCY_NAMES } from '../src/i18n/currencies/index.ts';
import { SUPPORTED_LANGUAGES } from '../src/i18n/locale.ts';
import { CLDR_TAG, build, parseListOne } from '../scripts/currency/generate.mjs';

// Producto 24A: the currency catalogue is generated from ISO 4217 and CLDR and committed. These
// checks run without network: the data's own invariants, its provenance, and the generator's
// refusals on synthetic sources. `npm run currency:generate -- --check` (with the cached sources)
// proves the committed files are exactly what the generator writes.
const root = new URL('../../../', import.meta.url);
const read = (path: string) => readFileSync(new URL(path, root), 'utf8');
const lock = JSON.parse(read('apps/mobile/scripts/currency/sources.lock.json'));

test('the generated data names its sources, and the lock records the exact bytes', () => {
  assert.equal(CLDR_VERSION, CLDR_TAG, 'the data was generated with the pinned CLDR release');
  assert.equal(lock.cldr, CLDR_TAG);
  const files = Object.keys(lock.files);
  assert.ok(files.includes('list-one.xml') && files.includes('currencyData.json') && files.includes('currencies-und.json'));
  for (const language of SUPPORTED_LANGUAGES) {
    assert.ok(files.includes(`currencies-${language}.json`) && files.includes(`territories-${language}.json`), 'names for ' + language);
  }
  for (const [file, entry] of Object.entries(lock.files) as [string, { url: string; sha256: string; bytes: number; retrieved: string }][]) {
    assert.match(entry.sha256, /^[0-9a-f]{64}$/, file);
    assert.ok(entry.bytes > 0, file);
    assert.match(entry.retrieved, /^\d{4}-\d{2}-\d{2}$/, file);
    if (file === 'list-one.xml') assert.match(entry.url, /^https:\/\/www\.six-group\.com\//);
    else assert.ok(entry.url.startsWith(`https://raw.githubusercontent.com/unicode-org/cldr-json/${CLDR_TAG}/`), file);
  }
  // Every generated file is exactly the generator's output: its sha256 is in the lock (CI has no cached sources).
  const outputs = lock.outputs as Record<string, string>;
  assert.deepEqual(Object.keys(outputs).sort(), ['packages/domain/currency-data.ts', ...SUPPORTED_LANGUAGES.map(language => `apps/mobile/src/i18n/currencies/${language}.ts`)].sort());
  for (const [path, hash] of Object.entries(outputs)) {
    assert.equal(createHash('sha256').update(readFileSync(new URL(path, root))).digest('hex'), hash, `${path} was edited by hand: run npm run currency:generate`);
  }
  const data = read('packages/domain/currency-data.ts');
  assert.match(data, /^\/\* GENERATED by apps\/mobile\/scripts\/currency\/generate\.mjs/);
  assert.ok(data.includes(`ISO 4217 List One published ${ISO_4217_PUBLISHED}`) && data.includes(`Unicode CLDR ${CLDR_VERSION}`));
  for (const language of SUPPORTED_LANGUAGES) assert.match(read(`apps/mobile/src/i18n/currencies/${language}.ts`), /^\/\* GENERATED by /);
  // The Unicode License v3 asks for its notice next to redistributed data.
  const license = read('LICENSES/Unicode-3.0.txt');
  assert.match(license, /UNICODE LICENSE V3/);
  assert.match(license, /Permission is hereby granted, free of charge/);
});

test('every language this build carries names every ready currency, from CLDR only', () => {
  assert.deepEqual(Object.keys(CURRENCY_NAMES).sort(), [...SUPPORTED_LANGUAGES].sort());
  for (const language of SUPPORTED_LANGUAGES) {
    const names = CURRENCY_NAMES[language];
    for (const code of currenciesWithStatus('ledger', 'ready')) {
      const forms = names.currencies[code];
      assert.ok(forms && forms.name && forms.one && forms.other, `${language} ${code}`);
    }
    for (const code of currenciesWithStatus('excluded')) assert.equal(names.currencies[code], undefined, `${language} names no excluded code (${code})`);
    for (const code of currenciesWithStatus('incomplete')) {
      assert.equal(currencyRecord(code).missing.includes('name:' + language), !names.currencies[code], `${language} ${code}: missing is exact`);
    }
    for (const region of new Set(CURRENCY_CODES.filter(code => currencyRecord(code).kind === 'fiat').flatMap(code => currencyRecord(code).territories))) {
      assert.equal(typeof names.territories[region], 'string', `${language} territory ${region}`);
    }
  }
  // The names FinanzApp has always shown are CLDR's plural forms.
  assert.equal(CURRENCY_NAMES.es.currencies.ARS?.other, 'pesos argentinos');
  assert.equal(CURRENCY_NAMES.es.currencies.USD?.other, 'dólares estadounidenses');
  assert.equal(CURRENCY_NAMES.en.currencies.ARS?.other, 'Argentine pesos');
  assert.equal(CURRENCY_NAMES.en.currencies.USD?.other, 'US dollars');
});

test('the catalogue today: 155 fiat currencies, two in the ledger, 151 ready for 24B, two incomplete', () => {
  const fiat = CURRENCY_CODES.filter(code => currencyRecord(code).kind === 'fiat');
  assert.equal(fiat.length, currenciesWithStatus('ledger', 'ready', 'incomplete').length);
  assert.deepEqual(currenciesWithStatus('ledger'), ['ARS', 'USD']);
  assert.deepEqual(currenciesWithStatus('incomplete'), ['SVC', 'VED']);
  assert.deepEqual([...currencyRecord('VED').missing], ['name:es', 'tender'], 'CLDR 48.2 has no Spanish name for the digital bolívar and marks it tender="false"');
  assert.deepEqual([...currencyRecord('SVC').missing], ['tender'], 'ISO keeps the colón active; El Salvador uses the dollar (CLDR)');
  assert.equal(currencyStatus('VES'), 'ready');
  assert.equal(currenciesWithStatus('ready').length, 151);
  assert.equal(currencyRecord('AR' + 'S' as IsoCurrencyCode).territories.join(), 'AR');
  assert.ok(currencyRecord('EUR').territories.includes('ES'));
});

const LIST = (entries: string) => `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<ISO_4217 Pblshd="2026-01-01"><CcyTbl>${entries}</CcyTbl></ISO_4217>`;
const ENTRY = (country: string, code: string, numeric: string, minor: string, fund = false) =>
  `<CcyNtry><CtryNm>${country}</CtryNm><CcyNm${fund ? ' IsFund="true"' : ''}>Name of ${code}</CcyNm><Ccy>${code}</Ccy><CcyNbr>${numeric}</CcyNbr><CcyMnrUnts>${minor}</CcyMnrUnts></CcyNtry>`;
const cldr = (lang: string, currencies: Record<string, object>) => JSON.stringify({ main: { [lang]: { numbers: { currencies } } } });
function sources(list: string, und: Record<string, object> = {}) {
  const names = { ARS: { displayName: 'peso', 'displayName-count-one': 'peso', 'displayName-count-other': 'pesos' },
    USD: { displayName: 'dólar', 'displayName-count-one': 'dólar', 'displayName-count-other': 'dólares' },
    EUR: { displayName: 'euro', 'displayName-count-other': 'euros' } };
  return {
    'list-one.xml': list,
    'currencyData.json': JSON.stringify({ supplemental: { currencyData: { fractions: { DEFAULT: { _digits: '2', _rounding: '0' }, JPY: { _digits: '0', _rounding: '0' } },
      region: { AR: [{ ARS: { _from: '1992-01-01' } }, { ARA: { _from: '1985-06-14', _to: '1992-01-01' } }], US: [{ USD: { _from: '1792-01-01' } }, { USS: { _from: '1965', _tender: 'false' } }],
        // A scheduled adoption (after the list's 2026-01-01 publication) and a currency that ended on that very day.
        DE: [{ EUR: { _from: '2026-06-01' } }], JP: [{ JPY: { _from: '1900-01-01', _to: '2026-01-01' } }] } } } }),
    'currencies-und.json': cldr('und', { USD: { symbol: 'US$', 'symbol-alt-narrow': '$' }, ARS: { 'symbol-alt-narrow': '$' }, ...und }),
    'currencies-es.json': cldr('es', names),
    'territories-es.json': JSON.stringify({ main: { es: { localeDisplayNames: { territories: { AR: 'Argentina', US: 'Estados Unidos' } } } } }),
  };
}

test('the generator reads ISO 4217 and CLDR, and refuses what it cannot classify', () => {
  const list = LIST(ENTRY('ARGENTINA', 'ARS', '032', '2') + ENTRY('UNITED STATES', 'USD', '840', '2') + ENTRY('ECUADOR', 'USD', '840', '2')
    + ENTRY('ANTARCTICA', '', '', '') .replace('<Ccy></Ccy><CcyNbr></CcyNbr><CcyMnrUnts></CcyMnrUnts>', '')
    + ENTRY('GERMANY', 'EUR', '978', '2') + ENTRY('JAPAN', 'JPY', '392', '0') + ENTRY('ZZ01', 'XAU', '959', 'N.A.') + ENTRY('BOLIVIA', 'BOV', '984', '2', true));
  const parsed = parseListOne(list);
  assert.equal(parsed.published, '2026-01-01');
  assert.deepEqual([...parsed.codes.keys()], ['ARS', 'USD', 'EUR', 'JPY', 'XAU', 'BOV'], 'a code used by two countries is one currency; a territory without one is skipped');
  const built = build(sources(list), ['es']);
  const byCode = Object.fromEntries(built.records.map(record => [record.code, record]));
  assert.equal(byCode.ARS.status, 'ready');
  assert.deepEqual(byCode.ARS.territories, ['AR'], 'a withdrawn peso (ARA, with _to) is not tender');
  assert.deepEqual(byCode.USD.territories, ['US'], 'a _tender="false" entry is not tender');
  assert.equal(byCode.USD.symbol, 'US$');
  assert.equal(byCode.ARS.symbol, 'ARS', 'no language-neutral symbol: the code');
  assert.equal(byCode.ARS.narrowSymbol, '$');
  assert.equal(byCode.JPY.digits, 0);
  assert.equal(byCode.JPY.status, 'incomplete', 'no Spanish name in the synthetic CLDR');
  assert.deepEqual(byCode.JPY.missing, ['name:es', 'tender'], 'no Spanish name, and no territory where it is tender (its range ended on the publication day)');
  assert.deepEqual(byCode.EUR.territories, [], 'a change scheduled after the ISO publication date is not tender yet');
  assert.equal(byCode.XAU.kind, 'metal');
  assert.equal(byCode.XAU.minorUnit, null);
  assert.equal(byCode.BOV.kind, 'fund');
  assert.equal(byCode.BOV.status, 'excluded');

  assert.throws(() => build(sources(LIST(ENTRY('ARGENTINA', 'ARS', '032', '2') + ENTRY('UNITED STATES', 'USD', '840', '2') + ENTRY('ZZ02', 'XQQ', '111', 'N.A.'))), ['es']),
    /XQQ has minor unit N\.A\. and no kind/, 'a new non-numeric code needs a decision');
  assert.throws(() => parseListOne(LIST(ENTRY('A', 'USD', '840', '2') + ENTRY('B', 'USD', '840', '3'))), /inconsistent/);
  assert.throws(() => parseListOne(LIST(ENTRY('A', 'USD', '840', '5'))), /minor unit 5/);
  assert.throws(() => parseListOne('<ISO_4217><CcyTbl/></ISO_4217>'), /Pblshd/);
  assert.throws(() => build(sources(LIST(ENTRY('ARGENTINA', 'ARS', '032', '2') + ENTRY('UNITED STATES', 'USD', '840', '2') + ENTRY('GERMANY', 'EUR', '978', '2')),
    { EUR: { symbol: 'US$' } }), ['es']), /Symbol US\$ names/, 'two currencies can never share a displayed symbol');
  assert.throws(() => build(sources(LIST(ENTRY('ARGENTINA', 'ARS', '032', '3') + ENTRY('UNITED STATES', 'USD', '840', '2'))), ['es']),
    /ARS must stay a ready currency with minor unit 2/, 'the ledger currencies can never change scale');
});

const CACHE = new URL('../i18n/work/currency-sources/list-one.xml', import.meta.url);
test('the committed catalogue is exactly what the generator writes from the locked sources', { skip: !existsSync(CACHE) && 'no cached sources (run npm run currency:generate -- --download)' }, () => {
  const output = execFileSync(process.execPath, ['--experimental-strip-types', '--no-warnings', fileURLToPath(new URL('../scripts/currency/generate.mjs', import.meta.url)), '--check'], { encoding: 'utf8' });
  assert.match(output, /Currency catalogue up to date/);
});
