import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { ISO_4217_PUBLISHED } from '@finanzapp/domain';
import { CURRENCY_DATA } from '../../../packages/domain/currency-data.ts';
import { REGIONS, RELEASED_REGIONS, SUPPORTED_LANGUAGES, completeConventions, type RegionCode } from '../src/i18n/locale.ts';
import { CLDR_REGIONS_VERSION, REGION_CODES, REGION_DATA, REGION_NAMES, type CatalogueRegionCode } from '../src/i18n/regions/index.ts';
import { catalogueConventions, catalogueRegionCode, conventionsForRegion, deviceRegion, isCatalogueRegion, regionChoices, regionDisplayName, regionStatus, searchRegions } from '../src/i18n/regions.ts';
import { CLDR_TAG, DELIBERATE_DEVIATIONS, build, currentTender, localeDirectory, parseDatePattern, parseGrouping, parseTimePattern, placeCodes, preferredHour12, verifyOutputs } from '../scripts/regions/generate.mjs';

// Producto 24R1: the region catalogue is generated from CLDR and committed. These checks run without
// network: the lock and the outputs' hashes, the data's own invariants, the generator's parsers on
// synthetic patterns and a synthetic build, the region API, and a cross-check of the pinned
// conventions against the ICU this Node carries. `npm run regions:generate -- --check` (with the
// cached sources) proves the committed files are exactly what the generator writes.
const root = new URL('../../../', import.meta.url);
const read = (path: string) => readFileSync(new URL(path, root), 'utf8');
const lock = JSON.parse(read('apps/mobile/scripts/regions/sources.lock.json'));

test('the generated data names its source, the lock records the exact bytes, and the committed outputs are the generator\'s', () => {
  assert.equal(CLDR_REGIONS_VERSION, CLDR_TAG, 'generated with the pinned CLDR release');
  assert.equal(lock.cldr, CLDR_TAG, 'the same release as the currency catalogue');
  assert.equal(CLDR_TAG, '48.2.0');
  const files = Object.keys(lock.files);
  for (const name of ['likelySubtags', 'weekData', 'timeData', 'codeMappings', 'territoryInfo', 'currencyData']) assert.ok(files.includes(name + '.json'), name);
  assert.ok(files.includes('availableLocales.json'));
  for (const language of SUPPORTED_LANGUAGES) assert.ok(files.includes(`territories-${language}.json`), 'names for ' + language);
  const localeFiles = files.filter(file => file.startsWith('numbers-'));
  assert.ok(localeFiles.length >= 150, 'one numbers.json per source locale: ' + localeFiles.length);
  for (const file of localeFiles) assert.ok(files.includes(file.replace('numbers-', 'ca-gregorian-')), file + ' has its dates file');
  for (const [file, entry] of Object.entries(lock.files) as [string, { url: string; sha256: string; bytes: number; retrieved: string }][]) {
    assert.match(entry.sha256, /^[0-9a-f]{64}$/, file);
    assert.ok(entry.bytes > 0, file);
    assert.match(entry.retrieved, /^\d{4}-\d{2}-\d{2}$/, file);
    assert.ok(entry.url.startsWith(`https://raw.githubusercontent.com/unicode-org/cldr-json/${CLDR_TAG}/`), file);
  }
  const outputs = lock.outputs as Record<string, string>;
  assert.deepEqual(Object.keys(outputs).sort(), ['apps/mobile/src/i18n/regions/data.ts', ...SUPPORTED_LANGUAGES.map(language => `apps/mobile/src/i18n/regions/${language}.ts`)].sort());
  for (const [path, hash] of Object.entries(outputs)) {
    assert.equal(createHash('sha256').update(readFileSync(new URL(path, root))).digest('hex'), hash, `${path} was edited by hand: run npm run regions:generate`);
    assert.match(readFileSync(new URL(path, root), 'utf8'), /^\/\* GENERATED by apps\/mobile\/scripts\/regions\/generate\.mjs/);
  }
  assert.deepEqual(verifyOutputs([...SUPPORTED_LANGUAGES].sort()), [], 'the offline verification CI runs');
  assert.match(read('LICENSES/Unicode-3.0.txt'), /UNICODE LICENSE V3/);
});

test('the catalogue lists every country and territory once, named in every language, with ISO mappings, conventions in Latin digits and tender the currency catalogue knows', () => {
  assert.equal(REGION_CODES.length, 257);
  assert.deepEqual([...REGION_CODES], [...REGION_CODES].sort(), 'sorted by code');
  assert.equal(new Set(REGION_CODES).size, REGION_CODES.length);
  for (const code of ['EU', 'EZ', 'UN', 'QO', 'ZZ', 'XA', 'XB', '001', '150', '419']) assert.equal(isCatalogueRegion(code), false, code + ' is not a place');
  for (const code of ['AR', 'US', 'JP', 'GB', 'IN', 'BR', 'XK', 'AQ', 'AC', 'AS']) assert.ok(isCatalogueRegion(code), code);
  const alpha3 = new Set<string>();
  for (const code of REGION_CODES) {
    const record = REGION_DATA[code];
    assert.match(code, /^[A-Z]{2}$/);
    for (const language of SUPPORTED_LANGUAGES) assert.ok(REGION_NAMES[language][code], `${code} named in ${language}`);
    if (record.alpha3) { assert.match(record.alpha3, /^[A-Z]{3}$/, code); assert.equal(alpha3.has(record.alpha3), false, code + ' alpha-3 unique'); alpha3.add(record.alpha3); }
    if (record.numeric) assert.match(record.numeric, /^\d{3}$/, code);
    assert.match(record.language, /^[a-z]{2,3}$/, code);
    assert.ok(record.sourceLocale.startsWith(record.language) || lock.files[`numbers-${record.sourceLocale}.json`], code + ' source locale');
    assert.ok(record.decimal.length === 1 && record.group.length >= 1 && record.decimal !== record.group, code + ' separators');
    assert.match(record.decimal, /^[.,]$/, code + ': Latin-script decimal (never Arabic-script digits, whatever the locale defaults to)');
    assert.equal(record.primaryGrouping, 3, code);
    assert.ok([2, 3].includes(record.secondaryGrouping), code);
    assert.ok([1, 2].includes(record.minimumGroupingDigits), code);
    assert.ok(['dmy', 'mdy', 'ymd'].includes(record.dateOrder), code);
    assert.ok(['/', '.', '-', ' '].includes(record.dateSeparator), code + ' separator ' + JSON.stringify(record.dateSeparator));
    assert.equal(typeof record.paddedDate, 'boolean', code);
    assert.equal(typeof record.hour12, 'boolean', code);
    assert.ok(Number.isInteger(record.weekStart) && record.weekStart >= 0 && record.weekStart <= 6, code);
    for (const currency of record.currencies) assert.ok(Object.hasOwn(CURRENCY_DATA, currency), `${code}: ${currency} is an ISO 4217 code`);
    if (record.dollarSignCurrency) {
      assert.ok(record.currencies.includes(record.dollarSignCurrency), code + ': a bare $ names a tender currency');
      assert.equal(CURRENCY_DATA[record.dollarSignCurrency as keyof typeof CURRENCY_DATA].narrowSymbol, '$', code);
    } else assert.equal(record.currencies.some(currency => CURRENCY_DATA[currency as keyof typeof CURRENCY_DATA]?.narrowSymbol === '$'), false, code + ': no $ tender, so no bare $');
  }
  // Lakh and crore: the Indian grouping, only where CLDR writes it.
  assert.deepEqual(REGION_CODES.filter(code => REGION_DATA[code].secondaryGrouping === 2), ['BD', 'BT', 'IN', 'NP']);
  // A handful of pinned facts, so a regenerated catalogue that silently changed them fails here.
  assert.deepEqual(REGION_DATA.JP, { alpha3: 'JPN', numeric: '392', continent: 'asia', language: 'ja', sourceLocale: 'ja', decimal: '.', group: ',', defaultDigits: 'latn', primaryGrouping: 3, secondaryGrouping: 3, minimumGroupingDigits: 1,
    dateOrder: 'ymd', dateSeparator: '/', paddedDate: true, datePattern: 'y/MM/dd', dayMonthPattern: 'M/d', timePattern: 'H:mm', hour12: false, weekStart: 0, currencies: ['JPY'], dollarSignCurrency: null });
  assert.deepEqual([REGION_DATA.GB.dateOrder, REGION_DATA.GB.paddedDate, REGION_DATA.GB.hour12, REGION_DATA.GB.weekStart, REGION_DATA.GB.currencies], ['dmy', true, false, 1, ['GBP']]);
  assert.deepEqual([REGION_DATA.DE.decimal, REGION_DATA.DE.group, REGION_DATA.DE.dateSeparator, REGION_DATA.DE.currencies], [',', '.', '.', ['EUR']]);
  assert.deepEqual([REGION_DATA.CH.decimal, REGION_DATA.CH.group, REGION_DATA.CH.dateSeparator], ['.', "'", '.']);
  assert.deepEqual([REGION_DATA.IN.secondaryGrouping, REGION_DATA.IN.hour12, REGION_DATA.IN.currencies], [2, true, ['INR']]);
  assert.deepEqual([REGION_DATA.KR.dateOrder, REGION_DATA.KR.dateSeparator, REGION_DATA.KR.hour12], ['ymd', '.', true]);
  assert.deepEqual([REGION_DATA.PA.currencies, REGION_DATA.PA.dollarSignCurrency, REGION_DATA.SV.currencies], [['PAB', 'USD'], 'USD', ['USD']]);
  assert.deepEqual([REGION_DATA.AS.language, REGION_DATA.AS.sourceLocale], ['sm', 'en-AS'], 'a likely language without CLDR data keeps its language and takes the region\'s English conventions');
  assert.equal(REGION_DATA.HU.minimumGroupingDigits, 2);
  assert.deepEqual([regionDisplayName('JP', 'es'), regionDisplayName('JP', 'en'), regionDisplayName('GB', 'es'), regionDisplayName('US', 'es'), regionDisplayName('US', 'en')], ['Japón', 'Japan', 'Reino Unido', 'Estados Unidos', 'United States']);
  assert.equal(ISO_4217_PUBLISHED, '2026-09-17', 'the day the tender was read on (the currency catalogue\'s)');
});

test('the released registry is what CLDR says about Argentina and the United States, except the one deliberate deviation, which is listed with its reason', () => {
  for (const code of ['AR', 'US'] as const) {
    const cldr = REGION_DATA[code], registry = completeConventions(REGIONS[code]);
    for (const key of ['decimal', 'group', 'dateOrder', 'dollarSignCurrency'] as const) assert.equal(registry[key], cldr[key], `${code} ${key}`);
    assert.equal(cldr.paddedDate, false, code + ': CLDR writes the short date unpadded, as the registry does');
    assert.equal(cldr.dateSeparator, '/', code);
    assert.equal(cldr.secondaryGrouping, 3, code);
  }
  assert.equal(REGION_DATA.US.hour12, REGIONS.US.hour12);
  assert.equal(REGION_DATA.AR.hour12, true, 'CLDR timeData prefers a 12-hour clock in Argentina');
  assert.equal(REGIONS.AR.hour12, false, 'FinanzApp keeps the 24-hour clock Argentines write (23.1C1)');
  assert.match(DELIBERATE_DEVIATIONS.AR.hour12, /24-hour clock/);
  assert.deepEqual(Object.keys(DELIBERATE_DEVIATIONS), ['AR'], 'every other field agrees');
  // The catalogue's conventions for a released region carry the registry's deliberate value, so 24R2 can switch the source without changing a string.
  assert.equal(catalogueConventions('AR').hour12, false);
  assert.equal(catalogueConventions('US').hour12, true);
  assert.equal(catalogueConventions('JP').hour12, false);
});

test('the generator\'s parsers: CLDR patterns for dates, times and grouping, the hour cycle, tender on a day, and the locale directory fallback', () => {
  assert.deepEqual(parseDatePattern('d/M/yy'), { dateOrder: 'dmy', dateSeparator: '/', paddedDate: false });
  assert.deepEqual(parseDatePattern('M/d/yy'), { dateOrder: 'mdy', dateSeparator: '/', paddedDate: false });
  assert.deepEqual(parseDatePattern('y/MM/dd'), { dateOrder: 'ymd', dateSeparator: '/', paddedDate: true });
  assert.deepEqual(parseDatePattern('dd.MM.yy'), { dateOrder: 'dmy', dateSeparator: '.', paddedDate: true });
  assert.deepEqual(parseDatePattern('yy. M. d.'), { dateOrder: 'ymd', dateSeparator: '.', paddedDate: false });
  assert.deepEqual(parseDatePattern('dd-MM-y'), { dateOrder: 'dmy', dateSeparator: '-', paddedDate: true });
  assert.deepEqual(parseDatePattern('d‏/M‏/y'), { dateOrder: 'dmy', dateSeparator: '/', paddedDate: false }, 'Arabic bidi marks are not separators');
  assert.deepEqual(parseDatePattern("d/M/yy 'G'"), { dateOrder: 'dmy', dateSeparator: '/', paddedDate: false }, 'a quoted literal is ignored');
  assert.throws(() => parseDatePattern('MM/y'), /supported way/);
  assert.throws(() => parseDatePattern('d|M|y'), /unexpected separator/);
  assert.equal(parseTimePattern('h:mm a'), true);
  assert.equal(parseTimePattern('HH:mm'), false);
  assert.equal(parseTimePattern("h:mm 'a'"), false, 'a quoted a is a literal');
  assert.deepEqual(parseGrouping('#,##0.###'), { primaryGrouping: 3, secondaryGrouping: 3 });
  assert.deepEqual(parseGrouping('#,##,##0.###'), { primaryGrouping: 3, secondaryGrouping: 2 });
  assert.deepEqual(parseGrouping('#0.###'), { primaryGrouping: 3, secondaryGrouping: 3 }, 'no grouping in the pattern: the default');
  assert.deepEqual([preferredHour12({ _preferred: 'h' }), preferredHour12({ _preferred: 'K' }), preferredHour12({ _preferred: 'H' }), preferredHour12({ _preferred: 'k' }), preferredHour12(undefined)], [true, true, false, false, null]);
  const salvador = [{ SVC: { _from: '1919-11-11' } }, { USD: { _from: '2001-01-01' } }];
  assert.deepEqual(currentTender(salvador, '2026-09-17'), ['SVC', 'USD']);
  assert.deepEqual(currentTender(salvador, '2000-12-31'), ['SVC']);
  assert.deepEqual(currentTender([{ ARA: { _from: '1985-06-14', _to: '1992-01-01' } }, { ARS: { _from: '1992-01-01' } }, { USN: { _tender: 'false' } }], '2026-09-17'), ['ARS']);
  assert.deepEqual(currentTender(undefined, '2026-09-17'), []);
  assert.equal(localeDirectory('ja-Jpan-JP', ['ja', 'en']), 'ja');
  assert.equal(localeDirectory('es-Latn-AR', ['es', 'es-AR']), 'es-AR');
  assert.equal(localeDirectory('zh-Hans-CN', ['zh', 'zh-Hans', 'zh-Hant']), 'zh-Hans');
  assert.throws(() => localeDirectory('sm-Latn-AS', ['en', 'en-AS']), /No cldr-json directory/);
  assert.deepEqual(placeCodes({ 'territoryInfo.json': JSON.stringify({ supplemental: { territoryInfo: { US: {}, EU: {}, '001': {}, ZZ: {}, AR: {}, XK: {} } } }) }), ['AR', 'US', 'XK']);
});

test('a synthetic build: two regions through the real generator, the English fallback of likely subtags, and the registry check that stops on an unlisted disagreement', () => {
  const main = (locale: string, numbers: object, dates: object) => ({ [`numbers-${locale}.json`]: JSON.stringify({ main: { [locale]: { numbers } } }),
    [`ca-gregorian-${locale}.json`]: JSON.stringify({ main: { [locale]: { dates: { calendars: { gregorian: dates } } } } }) });
  const files: Record<string, string> = {
    'territoryInfo.json': JSON.stringify({ supplemental: { territoryInfo: { AR: {}, US: {}, EU: {} } } }),
    'likelySubtags.json': JSON.stringify({ supplemental: { likelySubtags: { und: 'en-Latn-US', 'und-AR': 'es-Latn-AR' } } }),
    'availableLocales.json': JSON.stringify({ availableLocales: { full: ['en', 'es', 'es-AR'] } }),
    'weekData.json': JSON.stringify({ supplemental: { weekData: { firstDay: { '001': 'mon', US: 'sun' } } } }),
    'timeData.json': JSON.stringify({ supplemental: { timeData: { '001': { _preferred: 'H' }, AR: { _preferred: 'h' }, US: { _preferred: 'h' } } } }),
    'codeMappings.json': JSON.stringify({ supplemental: { codeMappings: { AR: { _alpha3: 'ARG', _numeric: '032' }, US: { _alpha3: 'USA', _numeric: '840' } } } }),
    'territoryContainment.json': JSON.stringify({ supplemental: { territoryContainment: { '019': { _contains: ['005', '021'] }, '005': { _contains: ['AR'] }, '021': { _contains: ['US'] } } } }),
    'currencyData.json': JSON.stringify({ supplemental: { currencyData: { region: { AR: [{ ARA: { _from: '1985-06-14', _to: '1992-01-01' } }, { ARS: { _from: '1992-01-01' } }], US: [{ USD: { _from: '1792-01-01' } }, { USN: { _tender: 'false' } }] } } } }),
    'territories-es.json': JSON.stringify({ main: { es: { localeDisplayNames: { territories: { AR: 'Argentina', US: 'Estados Unidos' } } } } }),
    'territories-en.json': JSON.stringify({ main: { en: { localeDisplayNames: { territories: { AR: 'Argentina', US: 'United States' } } } } }),
    ...main('es-AR', { 'symbols-numberSystem-latn': { decimal: ',', group: '.' }, 'decimalFormats-numberSystem-latn': { standard: '#,##0.###' } }, { dateFormats: { short: 'd/M/yy' }, timeFormats: { short: 'HH:mm' } }),
    ...main('en', { 'symbols-numberSystem-latn': { decimal: '.', group: ',' }, 'decimalFormats-numberSystem-latn': { standard: '#,##0.###' }, minimumGroupingDigits: '1' }, { dateFormats: { short: 'M/d/yy' }, timeFormats: { short: 'h:mm a' } }),
  };
  const currencies = { catalogue: { ARS: { narrowSymbol: '$' }, USD: { narrowSymbol: '$' }, USN: { narrowSymbol: 'USN' } }, published: '2026-09-17' };
  const registry = { AR: { decimal: ',', group: '.', dateOrder: 'dmy', hour12: false, dollarSignCurrency: 'ARS' }, US: { decimal: '.', group: ',', dateOrder: 'mdy', hour12: true, dollarSignCurrency: 'USD' } };
  const { records } = build(files, ['en', 'es'], currencies, registry);
  assert.deepEqual(records.map((record: { code: string }) => record.code), ['AR', 'US'], 'EU is not a place');
  assert.deepEqual(records[0], { code: 'AR', alpha3: 'ARG', numeric: '032', continent: 'americas', language: 'es', sourceLocale: 'es-AR', decimal: ',', group: '.', defaultDigits: 'latn', primaryGrouping: 3, secondaryGrouping: 3, minimumGroupingDigits: 1,
    dateOrder: 'dmy', dateSeparator: '/', paddedDate: false, datePattern: 'd/M/y', dayMonthPattern: 'd/M', timePattern: 'HH:mm', hour12: true, weekStart: 1, currencies: ['ARS'], dollarSignCurrency: 'ARS' });
  assert.deepEqual([records[1].language, records[1].sourceLocale, records[1].weekStart, records[1].currencies, records[1].hour12], ['en', 'en', 0, ['USD'], true], 'und-US is absent: the bare und entry with the region put back');
  assert.throws(() => build(files, ['en', 'es'], currencies, { ...registry, US: { ...registry.US, hour12: false } }), /US: the catalogue disagrees with REGIONS \(hour12: CLDR true, REGIONS false\)/);
  assert.throws(() => build(files, ['en', 'es'], currencies, { ...registry, JP: registry.AR }), /JP is in REGIONS but not in the catalogue/);
  assert.throws(() => build({ ...files, 'territoryContainment.json': JSON.stringify({ supplemental: { territoryContainment: { '019': { _contains: ['005'] }, '005': { _contains: ['AR'] } } } }) }, ['en', 'es'], currencies, registry),
    /US is in no continent/, 'a place outside every continent stops the generator');
  assert.throws(() => build({ ...files, 'territories-en.json': JSON.stringify({ main: { en: { localeDisplayNames: { territories: { AR: 'Argentina' } } } } }) }, ['en', 'es'], currencies, registry), /US has no name in en/);
});

test('the region API: codes, status against a gate, the fallback that never impersonates a region, the device Region, names, ordering and search', () => {
  assert.deepEqual([catalogueRegionCode(' jp '), catalogueRegionCode('ar'), catalogueRegionCode('ZZ'), catalogueRegionCode('EU'), catalogueRegionCode(''), catalogueRegionCode(null), catalogueRegionCode(['JP'])], ['JP', 'AR', null, null, null, null, null]);
  assert.deepEqual(['AR', 'US', 'JP', 'ZZ', 'ar', 'XK', 'SA', 'NP'].map(code => regionStatus(code)), ['released', 'released', 'released', 'unknown', 'released', 'released', 'catalogue', 'catalogue'],
    '24R2B: Japan and Kosovo released; Saudi Arabia and Nepal (native digits) blocked');
  assert.deepEqual(regionStatus('US', ['AR']), 'catalogue', 'a narrower gate: known but not honoured');
  const saudi = conventionsForRegion('SA');
  assert.deepEqual([saudi.region, saudi.source, saudi.requested], ['AR', 'default', 'SA'], 'Saudi Arabia is not released: the default conventions, and the screen can say so');
  assert.deepEqual(saudi.conventions, completeConventions(REGIONS.AR));
  assert.deepEqual([conventionsForRegion('JP').region, conventionsForRegion('JP').source], ['JP', 'released']);
  const states = conventionsForRegion('us');
  assert.deepEqual([states.region, states.source, states.requested, states.conventions.hour12, states.conventions.dateOrder], ['US', 'released', 'US', true, 'mdy']);
  assert.deepEqual([conventionsForRegion('ZZ').source, conventionsForRegion('ZZ').requested, conventionsForRegion(undefined).region], ['default', null, 'AR']);
  assert.deepEqual([conventionsForRegion('US', ['AR']).region, conventionsForRegion('US', ['AR']).source], ['AR', 'default']);
  assert.deepEqual([conventionsForRegion('AR', ['US']).region, conventionsForRegion('AR', ['US']).source], ['US', 'default'], 'without Argentina released the first released region stands in');
  // The device's Region setting, never a language, never a location.
  assert.equal(deviceRegion([{ languageTag: 'ja-JP', languageCode: 'ja', regionCode: 'JP' }]), 'JP');
  assert.equal(deviceRegion([{ languageTag: 'en-GB' }]), 'GB', 'only Intl answered: the tag\'s region');
  assert.equal(deviceRegion([{ languageTag: 'es-AR', regionCode: 'JP' }, { languageTag: 'en-US', regionCode: 'US' }]), 'JP', 'the Region setting of the first locale, not a second language');
  assert.equal(deviceRegion([{ languageTag: 'ar' }]), null, 'Arabic is a language, not Argentina');
  assert.equal(deviceRegion([{ languageTag: 'zh-Hant-TW' }]), 'TW');
  assert.equal(deviceRegion([{ languageTag: 'en', regionCode: 'ZZ' }]), null);
  assert.equal(deviceRegion([]), null);
  // Names and ordering in the language: the collator where the engine has one, a folding comparison otherwise; both alphabetical.
  const spanish = regionChoices('es'), english = regionChoices('en');
  assert.equal(spanish.length, 257);
  assert.deepEqual(spanish.slice(0, 4).map(choice => choice.name), ['Afganistán', 'Albania', 'Alemania', 'Andorra']);
  assert.deepEqual(english.slice(0, 3).map(choice => choice.name), ['Afghanistan', 'Åland Islands', 'Albania'], 'Å files under A');
  assert.ok(spanish.findIndex(choice => choice.code === 'JP') > spanish.findIndex(choice => choice.code === 'IT'), 'Japón after Italia');
  const usa = spanish.find(choice => choice.code === 'US')!;
  assert.equal(usa.name, 'Estados Unidos');
  assert.ok(usa.searchText.includes('usa') && usa.searchText.includes('840') && usa.searchText.includes('usd') && usa.searchText.includes('estados unidos'));
  // Search: exact code, code prefix, name prefix, any match (name, alpha-3, numeric code, tender currency), accents and case ignored.
  const first = (query: string, choices = spanish) => searchRegions(query, choices)[0]?.code;
  assert.deepEqual([first('jp'), first('JPN'), first('392'), first('japón'), first('Japon'), first('jpy'), first('ar'), first('arg')], ['JP', 'JP', 'JP', 'JP', 'JP', 'JP', 'AR', 'AR']);
  assert.equal(searchRegions('reino', spanish)[0].code, 'GB');
  assert.ok(searchRegions('reino', spanish).every(choice => choice.searchText.includes('reino')));
  assert.deepEqual(searchRegions('ar', spanish).slice(0, 2).map(choice => choice.code), ['AR', 'SA'], 'the exact code, then the name prefixes ("Arabia Saudita") in alphabetical order');
  assert.ok(searchRegions('eur', english).some(choice => choice.code === 'DE') && searchRegions('eur', english).some(choice => choice.code === 'FR'));
  assert.deepEqual(searchRegions('xyzzy', spanish), []);
  assert.equal(searchRegions('', spanish).length, 257, 'an empty query lists everything');
  assert.deepEqual(regionChoices('es', ['US', 'AR']).map(choice => choice.code), ['AR', 'US'], 'a subset keeps the alphabetical order');
});

test('the pinned conventions agree with the ICU this Node carries for a curated set of regions; Arabic-script defaults and skeleton dates are the known divergences', () => {
  // Both read CLDR (Node: ICU 78 / CLDR 48; the catalogue: cldr-json 48.2.0). The curated set avoids the two documented
  // differences: locales whose default numbering system is not Latin (the catalogue writes Latin digits on purpose) and
  // the few regions whose yMd skeleton orders the fields unlike the short pattern the catalogue follows.
  const curated: CatalogueRegionCode[] = ['AR', 'US', 'JP', 'IN', 'GB', 'DE', 'FR', 'BR', 'CH', 'KR', 'MX', 'CL', 'ES', 'IT', 'NL', 'AU', 'CA', 'RU', 'TR', 'ID', 'ZA', 'SE', 'PL', 'NG', 'UY', 'CO', 'PE'];
  for (const code of curated) {
    const record = REGION_DATA[code];
    const parts = new Intl.NumberFormat(record.sourceLocale, { useGrouping: true }).formatToParts(1234567.5);
    assert.equal(parts.find(part => part.type === 'decimal')?.value, record.decimal, code + ' decimal');
    assert.equal(parts.find(part => part.type === 'group')?.value, record.group, code + ' group');
    const integers = parts.filter(part => part.type === 'integer').map(part => part.value.length);
    assert.equal(integers.length > 2 ? integers[1] : 3, record.secondaryGrouping, code + ' secondary grouping');
    const date = new Intl.DateTimeFormat(record.sourceLocale, { year: 'numeric', month: 'numeric', day: 'numeric' }).formatToParts(new Date(2026, 8, 22));
    const order = date.filter(part => ['year', 'month', 'day'].includes(part.type)).map(part => part.type[0]).join('');
    assert.equal({ dmy: 'dmy', mdy: 'mdy', ymd: 'ymd' }[order] ?? order, record.dateOrder, code + ' date order');
    const hour = new Intl.DateTimeFormat(record.sourceLocale, { hour: 'numeric' }).resolvedOptions().hour12;
    if (code !== 'AR') assert.equal(hour, record.hour12, code + ' clock');
  }
});
